name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          # extended: true
        
      - name: Build hugo
        run: hugo --gc --minify
        
      - name: Git init
        run: |
            git config --global user.name '${{github.actor}}'
            git config --global user.email '${{github.actor}}@users.noreply.github.com'
            
      - name: Git add
        run: git add --force public/
      
      - name: Git commit
        run: git commit -m "publish"
  
      - name: Push public to branch
        run: |
            git subtree split --branch public --prefix public/
            git push -f origin public:public
            git branch -D public
