name: Deploy
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{secrets.GH_PAT}}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./wedding
          SCRIPT_MODE: true
